@baseUrl = http://localhost:5001/api

### Login User
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "johngmail.com",
  "password": "Password123"
}


### Signup User
POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john@gmail.com",
  "password": "Password@123"
}

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
### Get Profile
GET {{baseUrl}}/profile
Authorization: Bearer {{token}}
